### PR TITLE
fix: bug #1999 解决虚拟滚动配合keep-alive，active数据恢复后页面卡顿、内存飙升的问题 tags/3.4.12

### PR DESCRIPTION
**Pull request by fengqshanl**
修复 bug 1999，解决虚拟滚动配合keep-alive，active数据恢复后页面卡顿、内存飙升的问题。

### CODE REVIEW

**Comment by fengqshanl** [comment]
重置 scroll 的时候把 虚拟滚动的 状态给重置了，导致 html 节点暴增，从 0 - 当前节点都渲染了，数据量小不会有明显问题，数据量大时会渲染大量节点，导致内存飙升、页面卡顿。

**Comment by fengqshanl** [comment]
可复现的链接： https://codesandbox.io/p/sandbox/vxe-table-3-x-vue-2-6-wen-ti-yan-shi-forked-74p4c7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly6zf21l00073b6nu92636jy%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly6zf21l00033b6ni6pit5bp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly6zf21l00043b6njeax9jqn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly6zf21l00063b6nm2f3q484%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly6zf21l00033b6ni6pit5bp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly6zf21l00023b6nmkz8y5ag%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fviews%252Fhome.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cly6zf21l00033b6ni6pit5bp%2522%252C%2522activeTabId%2522%253A%2522cly6zf21l00023b6nmkz8y5ag%2522%257D%252C%2522cly6zf21l00063b6nm2f3q484%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly6zf21l00053b6n9nr7ubpa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2523%252Fpage1%2522%257D%255D%252C%2522id%2522%253A%2522cly6zf21l00063b6nm2f3q484%2522%252C%2522activeTabId%2522%253A%2522cly6zf21l00053b6n9nr7ubpa%2522%257D%252C%2522cly6zf21l00043b6njeax9jqn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cly6zf21l00043b6njeax9jqn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by fengqshanl** [comment]
操作步骤在上面写明了，问题也在上面标明了。

**Comment by fengqshanl** [comment]
链接代码使用的行比较少（200行），如果使用超多行时会导致内存飙升、页面卡死等问题。

**Comment by xuliangzhan** [comment]
确实，这个是 clearScroll 重置了 startIndex，没有处理 endIndex，同时处理一下就可以了

**Pull request merged**
